### ISSUE TITLE
Responsive.

### ISSUE THREAD

**Issue by imrtls00** [rascui/website#1]
Make the site responsive for mobile screens

**Comment by burhanharoon** [comment]
Hey @imrtls00, I checked out the website on my phone and it looks pretty good. Can you tell me more about what you want to change? Thanks!

**Comment by imrtls00** [comment]
Thanks @burhanharoon 🤝

**Comment by imrtls00** [comment]
Meanwhile, you can help identify more issues on the website.
Just create a new issue if you find one.
