### ISSUE TITLE
Addition of a button and a section

### ISSUE THREAD

**Issue by Zoha-Waheed** [rascui/website#103]
Add a button of "Faculty Advisor" , at the designated point in the given picture, also add box with picture of Sir Wajahat given below, and like it to the button too.
![WhatsApp Image 2023-11-27 at 2 30 33 AM](https://github.com/rascui/website/assets/128237901/83d1a5a0-b2ed-441b-928d-5190257386ee)
![images (1) (1)](https://github.com/rascui/website/assets/128237901/a7600d4f-c730-4c2b-af66-141bde97c472)

**Comment by saadman-galib** [comment]
I would like to attempt to solve it.
