### ISSUE TITLE
Updates for Marketing MECHS

### ISSUE THREAD

**Issue by Zoha-Waheed** [rascui/website#106]
Update Coordinator and Chief of MARKETING Mechs as per described below;
Chief: Moiz ud din
Coordinator: Suleiman Butt
(Search for data in members section; images and links, if not there then add, EVA picture, that is also available in given code file)

For reference, Sections that needs to be updated are given below.
![Capture](https://github.com/rascui/website/assets/128237901/5d319287-4a11-4675-b4d4-6ef12763ee1b)
![Capture1](https://github.com/rascui/website/assets/128237901/29dcab66-9788-41d8-9673-ea9b64f8a249)

**Comment by Saadaan-Hassan** [comment]
Assign this to me

**Comment by Zoha-Waheed** [comment]
Assigned...go for it
