### ISSUE TITLE
Updates for Design Dynamos

### ISSUE THREAD

**Issue by Zoha-Waheed** [rascui/website#107]
Update Coordinator and Chief of DESIGN DYNAMOS as per described below;
Chief: Abdur Rahman Nadeem
Coordinator: Sahibzadi Manal Zahra
(Linkedinn profile link:https://www.linkedin.com/in/manal-zahra-86a170288?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app )

**(Search for data in members section; images and links, if not there then add, EVA picture, that is also available in given code file)**

For reference, Sections that needs to be updated are given below.

![Capture4](https://github.com/rascui/website/assets/128237901/bb750379-70e2-4cb9-87df-ba15097b4c1e)
![Capture2](https://github.com/rascui/website/assets/128237901/f52394cc-9d2e-41be-9b91-fbc8df2088fc)

**Comment by Saadaan-Hassan** [comment]
Assign this to me

**Comment by manal-zahra** [comment]
Assign this to me.

**Comment by Zoha-Waheed** [comment]
Go for it.....
