### ISSUE TITLE
Update for SOCIAL STORMS

### ISSUE THREAD

**Issue by Zoha-Waheed** [rascui/website#108]
Update Coordinator and Chief of Social Storms as per described below;
Chief: Fatima Saqib
Coordinator: Saad Rehan
**(Search for data in members section; images and links, if not there then add, EVA picture, that is also available in given code file)**

For reference, Sections that needs to be updated are given below.
![Capture5](https://github.com/rascui/website/assets/128237901/08306f14-a3cc-4e0b-bb9d-755b73f3304b)

![Capture6](https://github.com/rascui/website/assets/128237901/a323f232-1722-4cc6-978b-d36b1e4bedb0)

**Comment by Saadaan-Hassan** [comment]
Assign this to me

**Comment by Zoha-Waheed** [comment]
Go for it
