### ISSUE TITLE
Update for EVENT ELITES

### ISSUE THREAD

**Issue by Zoha-Waheed** [rascui/website#109]
Update Coordinator and Chief of EVENT ELITES as per described below;
Chief: Muhammad Abdullah
Coordinator: Umair Amjad

(Search for data in members section; images and links, if not there then add, EVA picture, that is also available in given code file)

For reference, Sections that needs to be updated are given below.
![Capture7](https://github.com/rascui/website/assets/128237901/4415f307-4fc6-466c-9d29-5b355bc55030)
![Capture8](https://github.com/rascui/website/assets/128237901/3afd2744-ad89-4613-9479-3b56586931f1)

**Comment by Saadaan-Hassan** [comment]
Assign this to me

**Comment by abduvert** [comment]
Assign it to me!

**Comment by Zoha-Waheed** [comment]
Go for it

**Comment by abduvert** [comment]
Thank you!!
