### ISSUE TITLE
Replace "Visit Profile" button with social media icon.

### ISSUE THREAD

**Issue by imrtls00** [rascui/website#11]
![image](https://github.com/rascui/website/assets/68025467/0534b4ae-9817-454d-a7dd-74b46d8efb23)

Change the button to the respective social icon at the appropriate place such that it looks good even on mobile screens.

One thing to note is use Instagram, LinkedIn icons depending on the profile link.

**Comment by Petsamuel** [comment]
Asign to me

**Comment by RiaMalvi** [comment]
Can you assign this to me?

**Comment by 12345rams** [comment]
I want to contribute.Assign me

**Comment by KSSaiTeja** [comment]
i am interested.. as per my knowledge.. this is very small issue.. please assign it to me. i will fix it less than a minute.. @imrtls00

**Comment by NishantKuthe** [comment]
assign this to me

**Comment by IbraheemHaseeb7** [comment]
kindly solve the issue and make a pull request....

**Comment by IbraheemHaseeb7** [comment]
Thank you @12345rams for your contribution
