### ISSUE TITLE
Update for CINEMATIC CYBORGS

### ISSUE THREAD

**Issue by Zoha-Waheed** [rascui/website#110]
Update Chief of CINEMATIC CYBORGS as per described below;
Chief: Muhammad Zubair

(Search for data in members section; images and links, if not there then add, EVA picture, that is also available in given code file)

For reference, Sections that needs to be updated are given below.
![Capture8](https://github.com/rascui/website/assets/128237901/5a9dcc4f-25e0-42d7-bf82-5dc797314a73)

**Comment by Saadaan-Hassan** [comment]
Assign this to me

**Comment by Zoha-Waheed** [comment]
Go for it
