### ISSUE TITLE
Coordinators not Cordinator

### ISSUE THREAD

**Issue by bbhupen** [rascui/website#16]
![image](https://github.com/rascui/website/assets/67063163/40effac5-db64-48b8-a5c5-37b56040ca3d)

The Cordinator in home page should be Coordinator

Typo Issue

**Comment by bbhupen** [comment]
May I take up this issue??

**Comment by IbraheemHaseeb7** [comment]
go for it @bbhupen

**Comment by imrtls00** [comment]
"Co-ordinators" please ;)

**Comment by bbhupen** [comment]
sure
