### ISSUE TITLE
Improve the file structure

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [rascui/website#20]
The current file structure looks kind of messy. Make it more elegant and fix the routing problems where necessary.

**Comment by beatrizsmerino** [comment]
Hi! I want to do this task, could you assign it to me?

**Comment by Zoha-Waheed** [comment]
Lets do it. Assign this to me

**Comment by IbraheemHaseeb7** [comment]
there is already a pull request in line for this task... @Zoha-Waheed
