### ISSUE TITLE
Fix the width and height of all the pictures

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [rascui/website#26]
as you can see in the picture given below... some pictures have different height and some have same. We want all the pictures to have exactly the same height just like the one with tick on it

![image](https://github.com/rascui/website/assets/81369271/a6e6848c-231c-4232-b50a-9eb2e112c186)

Make sure to fix all the pictures using some generic method like `object-fit property` in CSS

**Comment by YashM211** [comment]
Can you assign this one to me

**Comment by IbraheemHaseeb7** [comment]
sure go ahead....just submit your PR @YashM211

**Comment by DevWeb13** [comment]
Hello,

I've reviewed the issue regarding the inconsistent image heights. I can take care of this and implement the object-fit property in CSS to ensure all images have the same height as the one with the tick mark.

Additionally, I have an alternative solution that might be of interest. I've developed a script that can crop all images to the desired size. Furthermore, it can also convert them to the WebP format (if they aren't already) to enhance performance. This could be beneficial for both consistent presentation and improved loading times.

Please let me know if you'd like me to proceed with this solution or if you have any other preferences.

Best regards,
LaReponseDev

**Comment by IbraheemHaseeb7** [comment]
@DevWeb13 can you work on webp format and submit your PR with respect to #7 as this issue is already assigned.

**Comment by 08Uzair** [comment]
Please assign this to me i will do this work in 1-2 hrs

**Comment by DevWeb13** [comment]
> @DevWeb13 can you work on webp format and submit your PR with respect to #7 as this issue is already assigned.

I noticed that issue number 7 was suggested for me to work on the webp format, however, I see that it's already assigned to someone else. Do you still want me to start on it? I want to make sure I'm not stepping on someone else's work or creating duplicates.

Best regards,
LaReponseDev



In the end, I decided to go ahead and do it anyway. I hope it meets your expectations. The Pull Request is now awaiting your review.
