### ISSUE TITLE
Convert the website to REACT project

### ISSUE THREAD

**Issue by imrtls00** [rascui/website#28]

**Comment by beatrizsmerino** [comment]
Hi @imrtls00 ! 😃
I want to do this task, could you please assign it to me?

**Comment by beatrizsmerino** [comment]
I am working on this assignment, please don't step on my toes. 🙏

**Comment by IbraheemHaseeb7** [comment]
sure go for it @beatrizsmerino

**Comment by beatrizsmerino** [comment]
Hi [imrtls00](https://github.com/imrtls00) and [IbraheemHaseeb7](https://github.com/IbraheemHaseeb7) !! 😊
This issue is solved into https://github.com/rascui/website/pull/45.
Could you take a look at it and merge it, please?
