### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by imrtls00** [rascui/website#3]

**Comment by Yash-Ainapure** [comment]
Heyy,I would like to contribute here.
Could you tell (in short)  that what all things do you need in README.md file that is must to be included? or any suggestions?
I also think that you can assign me this issue please.
Thank you.

**Comment by KSSaiTeja** [comment]
i have gone through the readme.md file.. there are some changes i will be suggest and make changes.. if i am assigned to this. i will fix them.
