### ISSUE TITLE
Change all the pictures paths to new webp format

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [rascui/website#35]
There is a new folder in the repo named as O-portfolio_webp. You must change all the paths of pictures in the [index.html](https://github.com/rascui/website/blob/main/index.html) to new webp pictures.

**Comment by Zoha-Waheed** [comment]
Assign this task to me.....

**Comment by IbraheemHaseeb7** [comment]
sure go for it @Zoha-Waheed

**Comment by IbraheemHaseeb7** [comment]
Thank you so much for your contribution @Zoha-Waheed
