### ISSUE TITLE
I want to add docker to Website 

### ISSUE THREAD

**Issue by Adidem23** [rascui/website#37]
Adding Docker to the website Can Improve user and Developer experience as you can access the code without local setup of files and folder

**Comment by IbraheemHaseeb7** [comment]
@Adidem23 hey that's a great idea. We are trying to shift the website to React first. Is it possible that we first address the issue #28 and then put it on the docker?

**Comment by Adidem23** [comment]
Yeah I will make Docker File According to react then no worries
