### ISSUE TITLE
Add RAS logo in Title

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [rascui/website#4]
the `Eva` logo should appear in the tab of this website. You can do it by putting the relevant code in the head section.

**Comment by Muz4mmil** [comment]
I can Fix that easily, Please Assign me this issue along with the logo

**Comment by shubhusion** [comment]
@IbraheemHaseeb7 kindly assign this issue to me.

**Comment by IbraheemHaseeb7** [comment]
@shubhusion @Muz4mmil 

You can use this logo to change the code [Eva](https://github.com/rascui/website/blob/main/O-portfolio/pictures/IEEE%20-%20Mascott.png)

and for submission just submit your pull request and we will merge it.

**Comment by IbraheemHaseeb7** [comment]
Completed by @Muz4mmil

**Comment by IbraheemHaseeb7** [comment]
@Muz4mmil the logo looks kind of compressed in terms of dimensions. Can you fix it?

**Comment by Muz4mmil** [comment]
I did that intentionally because the source logo was big in size.
But if required I can fix it

**Comment by imrtls00** [comment]
Use [this link](https://website-rascui.vercel.app/) for live updates.

**Comment by IbraheemHaseeb7** [comment]
> I did that intentionally because the source logo was big in size. But if required I can fix it

yes kindly fix it. It doesn't look good this way

**Comment by Muz4mmil** [comment]
> > I did that intentionally because the source logo was big in size. But if required I can fix it
> 
> yes kindly fix it. It doesn't look good this way

Done

**Comment by IbraheemHaseeb7** [comment]
Thank you @Muz4mmil for your contribution 🚀
