### ISSUE TITLE
Code Repeatation

### ISSUE THREAD

**Issue by Muz4mmil** [rascui/website#42]
**CODE REPEATATION**
the code is repeated for every member card which is not an efficient way.
Members data can be stored in a JSON file and then can be fetched in Reusable components.
This way, we don't have to make changes on every card for any front-end change. Also it makes it easy to add new members, delete, or modify existing members.

Assign me this issue under HacktoberFest and I can Implement This

**Comment by IbraheemHaseeb7** [comment]
hi @Muz4mmil I appreciate your idea...the thing is that the website is already being shifted to React where this idea is very likely to be addressed. Perhaps you can coordinate with the assigned person on this issue #28 . If you guys don't have any merge conflicts you can work on this issue.
