### ISSUE TITLE
UI/UX for a contributors page

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [rascui/website#47]
We want to add a contributors page to our link to give importance to the wonderful contributors we have on this repo. For it we need a ui design. You can create your figma designs and share with us here. Make sure to follow the existing website's theme otherwise your design will be rejected.

To submit your PR, create a folder named `Contributors` and just add the link of your figma file in some txt file

**Comment by mukeshmx** [comment]
I would like to work on this, please assign it to me.

**Comment by IbraheemHaseeb7** [comment]
sure go for it @mukeshmx . The best design will be implemented, there are no assignees to this issue
