### ISSUE TITLE
Typos 

### ISSUE THREAD

**Issue by SulaimanBUTT** [rascui/website#50]
robotic - robotics
year's - years
Excelence 
, app develoment,
databses
of community
no matter you
student wek
rubrics cube
reserved

**Comment by SulaimanBUTT** [comment]
I would like to contribute. Please assign this issue to me

**Comment by Zoha-Waheed** [comment]
Assign this task to me..........2nd one on go

**Comment by IbraheemHaseeb7** [comment]
there is no assignee to this issue......whoever submits it first....their PR will be merged. @SulaimanBUTT @Zoha-Waheed

**Comment by IbraheemHaseeb7** [comment]
thank you for the contribution @SulaimanBUTT
