### ISSUE TITLE
[bug]: Update Copyright Section to Dynamically Display Current Year 

### ISSUE THREAD

**Issue by purnasth** [rascui/website#51]
# Issue Title: Update Copyright Section to Dynamically Display Current Year

## Issue Description:
The current copyright section of the website reflects the year "2023". To avoid the need to manually update this section every year, I propose implementing a JavaScript solution. The goal is to have the year dynamically displayed, ensuring it automatically updates to the current year.

## Proposed Changes:
- Implement JavaScript functionality to dynamically fetch and display the current year in the copyright section.

## Attachments
![image](https://github.com/rascui/website/assets/107195487/52fa4381-cd79-4736-bb67-a09524003a80)

## Additional Information:
By using JavaScript to automate the update of the copyright year, the website will always display the current year. This enhancement streamlines the maintenance process and ensures the website's footer remains up-to-date without manual intervention.

Please assign this issue to me so that I can start working on it. Thank you for considering this improvement.

**Comment by IbraheemHaseeb7** [comment]
sure go for it @purnasth
