### ISSUE TITLE
Fix responsive design (Burger Menu Button)

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [rascui/website#61]
The burger menu is hidden in mobile. Need to fix this responsive design

![image](https://github.com/rascui/website/assets/81369271/833e7208-2226-464a-b783-aa6c3569b0da)

**Comment by harshvyas-22** [comment]
i would love to contribute please assign to me

**Comment by IbraheemHaseeb7** [comment]
go for it @harshvyas-22

**Comment by IbraheemHaseeb7** [comment]
this issue has been resolved in this PR #66
