### ISSUE TITLE
[BUG]: Drop Down not working on Contributors Page

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [rascui/website#69]
**Describe the bug**
The drop down menu (Burger Menu) not working on contributors page in mobile design

**Expected behavior**
The menu should work and all the links should be working.

**Screenshots**
![image](https://github.com/rascui/website/assets/81369271/14d108a6-ae48-4997-bc67-4e0d0fb1db92)

**Comment by thezeeshann** [comment]
@IbraheemHaseeb7 can you assign me this issue

**Comment by Shubhangam333** [comment]
Hey, I would like to work on this ,  Assign it to me

**Comment by Emm-dev0** [comment]
I would like to work on this. Kindly assign it to me

**Comment by IbraheemHaseeb7** [comment]
go for it @Emm-dev0

**Comment by Emm-dev0** [comment]
Thanks @IbraheemHaseeb7   on it.

**Comment by saadman-galib** [comment]
@Emm-dev0 Have you started working on this issue?

**Comment by Emm-dev0** [comment]
Yes I have

**Comment by saadman-galib** [comment]
@Emm-dev0  Oh I have solved this issue. Should I make a pull request?

**Comment by Emm-dev0** [comment]
It's fine you can, I learnt from your file structuring, thank you very much. I will just pull the update from you. Also can u explain to me how you solved it. Thanks

**Comment by saadman-galib** [comment]
It was a one line solve. As the navbar dropdown code is already written in script.js. I have just imported it into contributors index.html.
![image](https://github.com/rascui/website/assets/73209315/14e834b1-7642-4ad7-8dde-04466fd2a911)

**Comment by Emm-dev0** [comment]
Thank you very much for the update, I am grateful, hoping to contributing to your future projects.
