### ISSUE TITLE
Use Lossless Compression on all Images on the website

### ISSUE THREAD

**Issue by Muz4mmil** [rascui/website#7]
### Website is slow and takes time to load
The reason is because of the large image size( Quality, not the dimensions ). That much high quality is not needed for websites unless they  are meant to be downloaded
Images and logos can be compressed in order to reduce load time and increase performance and optimization of the website.

Assign me this task under Hacktoberfest. and i can complete it

**Comment by imrtls00** [comment]
Thanks @Muz4mmil.

Let's do this.
Assigned!

Use lossless compression and .webp formats...

**Comment by Muz4mmil** [comment]
> Thanks @Muz4mmil.
> 
> Let's do this. Assigned!
> 
> Use lossless compression and .webp formats...

Created the pull request.
Now the website will load faster and perform better,  
( Now it consumes 17mb instead of ~33mb )
If required, I can revert back to original images.
