### ISSUE TITLE
[FEATURE] Redesign this card

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [rascui/website#70]
**Is your feature request related to a problem? Please describe.**
The already implemented design does not really look too good as it also cuts the faces as well. Redesign this card to perhaps a pleasing design

**Describe the solution you'd like**
Perhaps the picture should be on top and the data can be on bottom

**Additional context**
![image](https://github.com/rascui/website/assets/81369271/92b21b22-41e5-45b4-91c0-e2179ed1aa7c)

**Comment by devharsh007** [comment]
Hey there! I would like to work on it ... please assign it to me !  
This under hactoberfect?
@IbraheemHaseeb7

**Comment by devharsh007** [comment]
Please assign it to me I have solved the photo issue! Do tell em if you need to redesign it, like pic on top and Indo at bottom?
@IbraheemHaseeb7

**Comment by devharsh007** [comment]
Can you  reassign me sorry ! Did that by mistake !

**Comment by IbraheemHaseeb7** [comment]
yes it is under hacktoberfest......and you can do the design something like this...

![image](https://github.com/rascui/website/assets/81369271/a94d83ff-6d6c-4369-a4ca-1ccbe17aec9c)

**Comment by Abhijeet-Bhushari** [comment]
I worked on this issue. 
I did not ask to assign it because I read the contributing.md where you asked to work on the issue and submit the PR directly. So I did that. 
Please accept this.
