### ISSUE TITLE
[BUG]: Hero Section is getting cropped on mobile screen

### ISSUE THREAD

**Issue by saadman-galib** [rascui/website#73]
Hero Section is getting cropped on the mobile screen
![image](https://github.com/rascui/website/assets/73209315/1e2236d9-2696-41a5-a5ff-0a74414b731a)

**Comment by saadman-galib** [comment]
@IbraheemHaseeb7  Can you assign it to me? I would like to solve this problem.

**Comment by IbraheemHaseeb7** [comment]
its first come first serve basis.....send your PR
