### ISSUE TITLE
[BUG]: Add Padding

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [rascui/website#78]
**Describe the bug**
Add padding of around 1rem only to above and top

**Expected behavior**
Padding should remove this cutting of the shadow even on hover

**Screenshots**
![image](https://github.com/rascui/website/assets/81369271/2b26fcb7-f009-47c9-aeb4-abbda83b0a64)
![image](https://github.com/rascui/website/assets/81369271/d7316ec3-4c6d-447c-9928-458ca407685c)

**Comment by manan18** [comment]
Hey @IbraheemHaseeb7 , Is this what you wanted?
![image](https://github.com/rascui/website/assets/96439888/dea9ddd4-051b-42de-828f-bd248d19ffc3)
![image](https://github.com/rascui/website/assets/96439888/84b17d44-7ce9-4a92-9c36-df572af92e17)

**Comment by manan18** [comment]
I've initiated a PR #83 . Please have a look @IbraheemHaseeb7 .
