### ISSUE TITLE
Make Grid equal in "Events & Seminars Section"

### ISSUE THREAD

**Issue by imrtls00** [rascui/website#8]
![image](https://github.com/rascui/website/assets/68025467/eb6907e9-5781-427d-abc9-2fba221e1bd4)

Make these boxes equal in size and submit a pull request for review.

**Comment by madhavgupta2002** [comment]
pls assign it to me

**Comment by RiaMalvi** [comment]
I want to work on this. Can you assign this to me?

**Comment by madhavgupta2002** [comment]
I have Submitted the PR @imrtls00 
kindly review!!!
thanks

**Comment by imrtls00** [comment]
@madhavgupta2002 the images are still not consistent.
Can you please make them consistent?

@RiaMalvi feel free to make the pull request if you can solve this issue, good luck!

![image](https://github.com/rascui/website/assets/68025467/ffc8a554-c829-4734-912b-ba0d3c461948)

**Comment by imrtls00** [comment]
@madhavgupta2002, @RiaMalvi please work on the latest commit as some other changes have been made.

**Comment by NishantKuthe** [comment]
assign this to me

**Comment by NishantKuthe** [comment]
I have submitted this pr please review it

**Comment by IbraheemHaseeb7** [comment]
Thank you @NishantKuthe for your contribution. 🙌🚀
