### ISSUE TITLE
Changing icons and their hyperlinks

### ISSUE THREAD

**Issue by Zoha-Waheed** [rascui/website#89]
![Screenshot (332)](https://github.com/rascui/website/assets/128237901/7f46efea-d59a-4b77-817f-44a00565894a)

As marked in the image, change the icons wherever such ones are and replace them with the Instagram or LinkedIn icon, respectively, with the follow-up code.
(Upon clicking the already present icon, it opens the website of RAS; that must not happen.)

**Comment by SulaimanBUTT** [comment]
I would like to solve this issue

**Comment by Zoha-Waheed** [comment]
ok its over to you now.

**Comment by abduvert** [comment]
Assign this to me

**Comment by Zoha-Waheed** [comment]
ok so assigning it to two @SulaimanBUTT and @abduvert , lets see who does it first
