### ISSUE TITLE
Make drop-shadows smoother on website (Easy)

### ISSUE THREAD

**Issue by imrtls00** [rascui/website#9]
Make sure all shadows on website look natural and smooth.
You can use something like [this tool](https://shadows.brumm.af/)

Please make sure the CSS is clean.

**Comment by Damon248** [comment]
Hey @imrtls00! I would like to work on this issue. Can you assign this to me?

**Comment by RiaMalvi** [comment]
I want to work on this. Can you assign this to me?

**Comment by Damon248** [comment]
Hey, @imrtls00! I have made the required changes already, can you please check out my pull request?

**Comment by imrtls00** [comment]
Thanks, @Damon248 can you please clone the latest main branch? There are small updates in the Team Section.

Also, try to make the shadows less black (i.e. don't use pure black as in #000000)

Meanwhile, @RiaMalvi feel free to fork this and make the pull request...
