### ISSUE TITLE
Create side buttons for easy slider movement

### ISSUE THREAD

**Issue by Zoha-Waheed** [rascui/website#90]
![Screenshot (3300)](https://github.com/rascui/website/assets/128237901/808dc0a8-104a-42b8-adf5-55b8049602c8)
As shown in the picture, add side buttons so that if someone wants to slide past quickly, don't have to wait for auto movement to go to the last one or desired one.

**Comment by prajwalgh** [comment]
Hello, if issue #90 is currently unassigned or available, please consider assigning it to me.

**Comment by jasonzubiate** [comment]
> Hello, if issue #90 is currently unassigned or available, please consider assigning it to me.

already sent a pr for it
