### ISSUE TITLE
[BUG]: Logo in the navbar is not showing

### ISSUE THREAD

**Issue by JohnPark24** [rascui/website#92]
**Describe the bug**
The logo in the navbar is not showing.

**Expected behavior**
The logo works but does not show.

**Screenshots**
![Screenshot 2023-11-08 205433](https://github.com/rascui/website/assets/62269310/5cfeb808-a671-4db7-ba50-8a04d7bf0dec)

**Additional context**
Problem happened using Edge but only sometimes

**Comment by saadman-galib** [comment]
@JohnPark24 But the logo is showing on my screen 
![image](https://github.com/rascui/website/assets/73209315/dc41bea4-ea5e-4e06-8724-bb36d1cff533)

**Comment by Zoha-Waheed** [comment]
@JohnPark24 the issue is not coming in general,  but your time is appreciable. So, waiting for some other good changes and issues from your side
