### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by Zoha-Waheed** [rascui/website#97]
From the "Fatima Saqib" card and below, the spelling for coordinator is written as cordinator multiple times.
Do it Coordinator everywhere.
In the "Eesha Irfan" card, the spelling for audience is written as audiance.
Rectify them.

**Comment by manal-zahra** [comment]
assign this to me please

**Comment by ranafahadaman1** [comment]
Assign it to me, I caught this issue.

**Comment by Zoha-Waheed** [comment]
Okay, have a lead!
