### ISSUE TITLE
Adding dots-rolling instead of slide-rolls

### ISSUE THREAD

**Issue by Zoha-Waheed** [rascui/website#98]
The slide rolls should be converted into balls or dots that will looks modern, you can see the reference example. Moreover, you can be creative too

![WhatsApp Image 2023-11-16 at 9 55 33 PM](https://github.com/rascui/website/assets/128237901/21e2717c-0b59-4608-b433-036d5e6c947d)

**Comment by IbraheemHaseeb7** [comment]
assign me pweaseeeeee

**Comment by Zoha-Waheed** [comment]
Okay, Have a lead to it.
Your time starts now........
